/** Canonical step definitions — snapshotted into ExportStepInstance at project create. */

const STEPS = {
  "product-readiness": {
    code: "product-readiness",
    title: "آماده‌سازی کالا و مشخصات",
    description: "مشخصات فنی، کیفیت، مقدار قابل عرضه و مدارک پایه محصول را تکمیل کنید.",
    phase: "prepare",
    order: 10,
    required: true,
    dependencies: [],
    defaultDocuments: ["Product specification", "Quality datasheet"],
    requiredOutput: "product_specs_confirmed",
    serviceKeys: ["goods-preparation", "export-packaging", "export-consulting"],
    toolLinks: [],
    responsibleParty: "seller",
    estimatedDuration: "1-3 روز",
    warnings: [],
    helpContent:
      "قبل از مذاکره صادراتی، مشخصات پایدار (گرید، رطوبت، خلوص، بسته‌بندی) را ثابت کنید تا اختلاف با خریدار کم شود.",
  },
  "market-selection": {
    code: "market-selection",
    title: "انتخاب و اعتبارسنجی بازار مقصد",
    description: "تقاضای مقصد، محدودیت‌های ورود و کانال فروش را بررسی کنید.",
    phase: "prepare",
    order: 20,
    required: true,
    dependencies: ["product-readiness"],
    defaultDocuments: [],
    requiredOutput: "target_market_confirmed",
    serviceKeys: ["market-development", "find-buyer", "export-consulting"],
    toolLinks: [],
    responsibleParty: "seller",
    estimatedDuration: "3-10 روز",
    warnings: [],
    helpContent: "کشور مقصد را فقط بر اساس قیمت انتخاب نکنید؛ مجوز ورود و استاندارد مقصد را هم بسنجید.",
  },
  "hs-code": {
    code: "hs-code",
    title: "تعیین کد HS",
    description: "طبقه‌بندی گمرکی کالا را مشخص و مستند کنید.",
    phase: "compliance",
    order: 30,
    required: true,
    dependencies: ["product-readiness"],
    defaultDocuments: ["HS classification note"],
    requiredOutput: "hs_code",
    serviceKeys: ["customs-clearance", "export-compliance"],
    toolLinks: [{ id: "hs-code", label: "ابزار HS Code", href: "/hs-code" }],
    responsibleParty: "seller",
    estimatedDuration: "1-5 روز",
    warnings: ["کد HS اشتباه می‌تواند جریمه یا توقف محموله ایجاد کند."],
    helpContent: "از ابزار HS زارعُون استفاده کنید و در صورت ابهام با کارشناس گمرک تأیید بگیرید.",
  },
  "export-restrictions": {
    code: "export-restrictions",
    title: "بررسی محدودیت‌ها و مجوزهای صادرات",
    description: "ممنوعیت‌ها، سهمیه‌ها، مجوزهای خاص مبدأ و مقصد را بررسی کنید.",
    phase: "compliance",
    order: 40,
    required: true,
    dependencies: ["hs-code", "market-selection"],
    defaultDocuments: ["Export permit checklist"],
    requiredOutput: "restrictions_cleared",
    serviceKeys: ["export-compliance", "customs-clearance"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "2-14 روز",
    warnings: [],
    helpContent: "برای برخی کالاها (کشاورزی، شیمیایی، دوکاربردی) مجوز جداگانه لازم است.",
  },
  certifications: {
    code: "certifications",
    title: "گواهی‌ها و استانداردهای لازم",
    description: "گواهی‌های مبدأ، بهداشت، کیفیت یا استاندارد مقصد را برنامه‌ریزی کنید.",
    phase: "compliance",
    order: 50,
    required: true,
    dependencies: ["export-restrictions"],
    defaultDocuments: ["Certificate of Origin"],
    requiredOutput: "certs_plan",
    serviceKeys: ["intl-certificates", "export-compliance"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "3-21 روز",
    warnings: [],
    helpContent: "لیست گواهی‌ها بر اساس خانواده کالا و مقصد به‌روز می‌شود.",
  },
  "laboratory-testing": {
    code: "laboratory-testing",
    title: "آزمایشگاه و آنالیز",
    description: "آنالیز کیفیت، ایمنی یا ترکیب شیمیایی مورد نیاز خریدار/مقصد.",
    phase: "compliance",
    order: 55,
    required: false,
    dependencies: ["product-readiness"],
    defaultDocuments: ["Certificate of Analysis", "Lab report"],
    requiredOutput: "lab_report",
    serviceKeys: ["laboratory-testing", "quality-inspection"],
    toolLinks: [],
    responsibleParty: "provider",
    estimatedDuration: "3-15 روز",
    warnings: [],
    helpContent: "نمونه نماینده محموله را برای آزمایش بفرستید.",
  },
  "phytosanitary": {
    code: "phytosanitary",
    title: "بهبرداشت / قرنطینه گیاهی",
    description: "گواهی بهداشت گیاهی یا قرنطینه برای محصولات کشاورزی خام.",
    phase: "compliance",
    order: 56,
    required: true,
    dependencies: ["certifications"],
    defaultDocuments: ["Phytosanitary Certificate"],
    requiredOutput: "phytosanitary_cert",
    serviceKeys: ["intl-certificates", "export-compliance"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "3-10 روز",
    warnings: ["بدون این گواهی بسیاری از مقاصد محموله کشاورزی را پذیرش نمی‌کنند."],
    helpContent: "از سازمان حفظ نباتات یا مرجع رسمی مبدأ اقدام کنید.",
  },
  "health-food-safety": {
    code: "health-food-safety",
    title: "سلامت غذایی و برچسب مقصد",
    description: "الزامات بهداشت غذایی، تاریخ مصرف و برچسب‌گذاری زبان مقصد.",
    phase: "compliance",
    order: 57,
    required: true,
    dependencies: ["certifications"],
    defaultDocuments: ["Health Certificate", "Label artwork"],
    requiredOutput: "food_safety_ok",
    serviceKeys: ["intl-certificates", "destination-labeling"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "5-20 روز",
    warnings: [],
    helpContent: "برچسب باید با قوانین مقصد (زبان، آلرژن، ارزش غذایی) سازگار باشد.",
  },
  "dangerous-goods": {
    code: "dangerous-goods",
    title: "کالای خطرناک (DG) و MSDS",
    description: "طبقه‌بندی DG، برگه ایمنی مواد، بسته‌بندی و حمل تخصصی.",
    phase: "compliance",
    order: 58,
    required: true,
    dependencies: ["hs-code"],
    defaultDocuments: ["MSDS / SDS", "DG declaration"],
    requiredOutput: "dg_cleared",
    serviceKeys: ["dangerous-goods-logistics", "cargo-insurance", "export-compliance"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "5-21 روز",
    warnings: ["حمل نادرست کالای خطرناک ریسک ایمنی و حقوقی جدی دارد."],
    helpContent: "طبقه‌بندی UN و محدودیت خطوط کشتیرانی/هوایی را زود بررسی کنید.",
  },
  "cold-chain": {
    code: "cold-chain",
    title: "زنجیره سرد و کنترل دما",
    description: "سردخانه، بسته‌بندی دمایی و لجستیک زنجیره سرد.",
    phase: "logistics",
    order: 59,
    required: true,
    dependencies: ["product-readiness"],
    defaultDocuments: ["Temperature log plan"],
    requiredOutput: "cold_chain_plan",
    serviceKeys: ["cold-chain-logistics", "export-packaging"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "3-14 روز",
    warnings: ["شکست دما می‌تواند کل محموله را غیرقابل فروش کند."],
    helpContent: "بازه دمایی هدف و نقاط کنترل را مکتوب کنید.",
  },
  pricing: {
    code: "pricing",
    title: "قیمت‌گذاری صادراتی",
    description: "قیمت FOB/CIF یا قیمت متناسب با Incoterm و هزینه‌های جانبی.",
    phase: "commercial",
    order: 60,
    required: true,
    dependencies: ["hs-code", "market-selection"],
    defaultDocuments: ["Export price sheet"],
    requiredOutput: "export_price",
    serviceKeys: ["export-consulting"],
    toolLinks: [
      { id: "unit-converter", label: "تبدیل واحد", href: "/unit-converter" },
      { id: "cbm", label: "محاسبه CBM", href: "/cbm" },
    ],
    responsibleParty: "seller",
    estimatedDuration: "1-5 روز",
    warnings: [],
    helpContent: "هزینه بسته‌بندی، بازرسی، مجوز و حمل را در حاشیه قیمت ببینید.",
  },
  "buyer-verification": {
    code: "buyer-verification",
    title: "اعتبارسنجی خریدار",
    description: "هویت، سابقه پرداخت و ریسک تحریم/کلاهبرداری خریدار را بررسی کنید.",
    phase: "commercial",
    order: 70,
    required: true,
    dependencies: ["market-selection"],
    defaultDocuments: [],
    requiredOutput: "buyer_verified",
    serviceKeys: ["export-compliance", "legal-contract"],
    toolLinks: [],
    responsibleParty: "seller",
    estimatedDuration: "2-10 روز",
    warnings: ["پیش‌پرداخت به حساب‌های ناشناس ندهید و مدارک شرکت را بگیرید."],
    helpContent: "برای معاملات بزرگ، LC یا اسکرو زارعُون را در نظر بگیرید.",
  },
  contract: {
    code: "contract",
    title: "قرارداد فروش صادراتی",
    description: "شرایط کیفیت، کمیت، تحویل، جریمه تأخیر و حل اختلاف را مکتوب کنید.",
    phase: "commercial",
    order: 80,
    required: true,
    dependencies: ["buyer-verification", "pricing"],
    defaultDocuments: ["Sales contract / PI"],
    requiredOutput: "signed_contract",
    serviceKeys: ["legal-contract"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "3-14 روز",
    warnings: [],
    helpContent: "Proforma Invoice و قرارداد باید با هم هم‌خوان باشند.",
  },
  "payment-method": {
    code: "payment-method",
    title: "روش پرداخت و تأمین مالی",
    description: "پیش‌پرداخت، LC، CAD، حساب باز یا اسکرو را نهایی کنید.",
    phase: "commercial",
    order: 90,
    required: true,
    dependencies: ["contract"],
    defaultDocuments: ["Payment terms"],
    requiredOutput: "payment_terms",
    serviceKeys: ["payment-and-escrow"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "2-21 روز",
    warnings: [],
    helpContent: "ریسک ارزی و زمان آزادسازی وجه را شفاف کنید.",
  },
  incoterms: {
    code: "incoterms",
    title: "انتخاب و درک Incoterm",
    description: "نقطه انتقال ریسک و هزینه بین فروشنده و خریدار را مشخص کنید.",
    phase: "commercial",
    order: 95,
    required: true,
    dependencies: ["pricing"],
    defaultDocuments: [],
    requiredOutput: "incoterm",
    serviceKeys: ["export-consulting"],
    toolLinks: [{ id: "incoterms", label: "راهنمای Incoterms", href: "/incoterms" }],
    responsibleParty: "shared",
    estimatedDuration: "1 روز",
    warnings: [],
    helpContent: "DDP بیشترین مسئولیت را روی فروشنده می‌گذارد؛ EXW کمترین را.",
  },
  "export-packaging": {
    code: "export-packaging",
    title: "بسته‌بندی صادراتی",
    description: "بسته‌بندی مقاوم حمل، پالت، تسمه‌کشی و استاندارد مقصد.",
    phase: "logistics",
    order: 100,
    required: true,
    dependencies: ["product-readiness", "incoterms"],
    defaultDocuments: ["Packing list draft"],
    requiredOutput: "packaging_ready",
    serviceKeys: ["export-packaging", "goods-preparation"],
    toolLinks: [{ id: "cbm", label: "محاسبه CBM", href: "/cbm" }],
    responsibleParty: "seller",
    estimatedDuration: "3-14 روز",
    warnings: [],
    helpContent: "وزن خالص/ناخالص و تعداد بسته را دقیق ثبت کنید.",
  },
  "destination-labeling": {
    code: "destination-labeling",
    title: "برچسب‌گذاری مقصد",
    description: "برچسب تجاری و الزامات زبانی/قانونی کشور مقصد.",
    phase: "logistics",
    order: 105,
    required: false,
    dependencies: ["export-packaging"],
    defaultDocuments: ["Label proof"],
    requiredOutput: "labels_ready",
    serviceKeys: ["destination-labeling"],
    toolLinks: [],
    responsibleParty: "seller",
    estimatedDuration: "2-10 روز",
    warnings: [],
    helpContent: "برای مواد غذایی و مصرفی، برچسب مقصد معمولاً اجباری است.",
  },
  "container-selection": {
    code: "container-selection",
    title: "انتخاب کانتینر و محاسبه حجم",
    description: "نوع کانتینر، CBM و چیدمان محموله برای حمل دریایی.",
    phase: "logistics",
    order: 110,
    required: false,
    dependencies: ["export-packaging"],
    defaultDocuments: [],
    requiredOutput: "container_plan",
    serviceKeys: ["international-logistics"],
    toolLinks: [{ id: "cbm", label: "ابزار CBM", href: "/cbm" }],
    responsibleParty: "shared",
    estimatedDuration: "1-3 روز",
    warnings: [],
    helpContent: "برای دریایی، CBM و وزن حداکثر کانتینر را همزمان چک کنید.",
  },
  "air-volumetric": {
    code: "air-volumetric",
    title: "وزن حجمی هوایی",
    description: "محاسبه chargeable weight برای حمل هوایی.",
    phase: "logistics",
    order: 111,
    required: false,
    dependencies: ["export-packaging"],
    defaultDocuments: [],
    requiredOutput: "air_chargeable_weight",
    serviceKeys: ["international-logistics"],
    toolLinks: [{ id: "cbm", label: "CBM / حجم", href: "/cbm" }],
    responsibleParty: "shared",
    estimatedDuration: "1 روز",
    warnings: [],
    helpContent: "در هوایی معمولاً max(وزن واقعی، وزن حجمی) مبنای کرایه است.",
  },
  "customs-documents": {
    code: "customs-documents",
    title: "تهیه اسناد گمرکی",
    description: "فاکتور تجاری، پکینگ‌لیست، گواهی مبدأ و سایر اسناد حمل.",
    phase: "customs",
    order: 120,
    required: true,
    dependencies: ["hs-code", "export-packaging", "contract"],
    defaultDocuments: ["Commercial Invoice", "Packing List", "Certificate of Origin"],
    requiredOutput: "docs_ready",
    serviceKeys: ["trade-documents", "customs-clearance"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "2-7 روز",
    warnings: [],
    helpContent: "اعداد فاکتور، پکینگ و اظهارنامه باید یکسان باشند.",
  },
  "customs-declaration": {
    code: "customs-declaration",
    title: "اظهار گمرکی مبدأ",
    description: "ثبت اظهارنامه صادرات و ترخیص از گمرک مبدأ.",
    phase: "customs",
    order: 130,
    required: true,
    dependencies: ["customs-documents", "export-restrictions"],
    defaultDocuments: ["Export declaration"],
    requiredOutput: "export_cleared",
    serviceKeys: ["customs-clearance"],
    toolLinks: [],
    responsibleParty: "provider",
    estimatedDuration: "1-7 روز",
    warnings: [],
    helpContent: "با حق‌العمل‌کار گمرک هماهنگ کنید.",
  },
  "destination-clearance": {
    code: "destination-clearance",
    title: "ترخیص مقصد (مسئولیت فروشنده)",
    description: "وقتی Incoterm مثل DDP است، ترخیص و عوارض مقصد بر عهده فروشنده است.",
    phase: "customs",
    order: 135,
    required: false,
    dependencies: ["customs-declaration", "incoterms"],
    defaultDocuments: ["Import clearance plan"],
    requiredOutput: "destination_cleared",
    serviceKeys: ["customs-clearance", "export-compliance"],
    toolLinks: [],
    responsibleParty: "seller",
    estimatedDuration: "3-21 روز",
    warnings: ["در DDP هزینه‌ها و ریسک مقصد را دست‌کم نگیرید."],
    helpContent: "نماینده محلی یا بروکر مقصد از قبل مشخص کنید.",
  },
  "freight-selection": {
    code: "freight-selection",
    title: "انتخاب حمل‌ونقل بین‌المللی",
    description: "مقایسه خطوط، زمان، هزینه و شرایط تحویل.",
    phase: "shipment",
    order: 140,
    required: true,
    dependencies: ["incoterms", "export-packaging"],
    defaultDocuments: ["Freight quote"],
    requiredOutput: "freight_booked",
    serviceKeys: ["international-logistics", "sea-freight", "air-freight"],
    toolLinks: [{ id: "cbm", label: "ابزار CBM", href: "/cbm" }],
    responsibleParty: "shared",
    estimatedDuration: "2-10 روز",
    warnings: [],
    helpContent: "رزرو را با تاریخ آماده‌بودن کالا هم‌زمان کنید.",
  },
  "cargo-insurance": {
    code: "cargo-insurance",
    title: "بیمه محموله",
    description: "پوشش بیمه متناسب با ارزش و مسیر حمل.",
    phase: "shipment",
    order: 150,
    required: false,
    dependencies: ["freight-selection", "pricing"],
    defaultDocuments: ["Insurance certificate"],
    requiredOutput: "insurance_done",
    serviceKeys: ["cargo-insurance"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "1-5 روز",
    warnings: [],
    helpContent: "در CIF/CIP معمولاً فروشنده بیمه را ترتیب می‌دهد.",
  },
  shipment: {
    code: "shipment",
    title: "بارگیری و ارسال",
    description: "تحویل به حمل‌کننده، دریافت بارنامه/AWB و رهگیری.",
    phase: "shipment",
    order: 160,
    required: true,
    dependencies: ["customs-declaration", "freight-selection"],
    defaultDocuments: ["Bill of Lading / AWB"],
    requiredOutput: "shipped",
    serviceKeys: ["international-logistics"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "1-5 روز",
    warnings: [],
    helpContent: "کپی بارنامه و عکس بارگیری را در پروژه بایگانی کنید.",
  },
  delivery: {
    code: "delivery",
    title: "تحویل به خریدار",
    description: "رسیدن محموله، تأیید دریافت و رفع مغایرت.",
    phase: "shipment",
    order: 170,
    required: true,
    dependencies: ["shipment"],
    defaultDocuments: ["Delivery confirmation"],
    requiredOutput: "delivered",
    serviceKeys: ["international-logistics"],
    toolLinks: [],
    responsibleParty: "shared",
    estimatedDuration: "بسته به مسیر",
    warnings: [],
    helpContent: "مغایرت کمّی/کیفی را فوری مستند کنید.",
  },
  "post-shipment": {
    code: "post-shipment",
    title: "پیگیری پس از ارسال",
    description: "وصول وجه، بازخورد خریدار و آماده‌سازی محموله بعدی.",
    phase: "aftercare",
    order: 180,
    required: true,
    dependencies: ["delivery"],
    defaultDocuments: [],
    requiredOutput: "closed",
    serviceKeys: ["payment-and-escrow", "export-consulting"],
    toolLinks: [],
    responsibleParty: "seller",
    estimatedDuration: "ongoing",
    warnings: [],
    helpContent: "پس از موفقیت، مدارک و هزینه‌های واقعی را برای محموله بعدی آرشیو کنید.",
  },
};

function getStepDefinition(code) {
  return STEPS[code] ? { ...STEPS[code] } : null;
}

module.exports = { STEPS, getStepDefinition };
