/**
 * Family templates: ordered step codes included by default.
 * Conditional steps are added/removed by rules engine.
 */
const FAMILY_TEMPLATES = {
  "agro-raw": {
    id: "agro-raw",
    titleFa: "محصولات کشاورزی خام",
    titleEn: "Raw agricultural products",
    descriptionFa: "مسیر صادرات محصولات کشاورزی خام مانند خرما، خشکبار، غلات و میوه.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "certifications",
      "phytosanitary",
      "laboratory-testing",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: { isFood: true, isAgroRaw: true, labSuggested: true },
  },
  "food-processed": {
    id: "food-processed",
    titleFa: "مواد غذایی و نوشیدنی",
    titleEn: "Processed food & beverages",
    descriptionFa: "مواد غذایی فرآوری‌شده، کنسرو، نوشیدنی و محصولات بسته‌بندی مصرفی.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "certifications",
      "health-food-safety",
      "laboratory-testing",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "destination-labeling",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: { isFood: true, isProcessedFood: true, labelingRequired: true },
  },
  "perishable-cold-chain": {
    id: "perishable-cold-chain",
    titleFa: "فاسدشدنی و سردخانه‌ای",
    titleEn: "Perishable / cold chain",
    descriptionFa: "محصولات حساس به دما که نیاز به زنجیره سرد دارند.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "certifications",
      "health-food-safety",
      "cold-chain",
      "laboratory-testing",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "destination-labeling",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: { isFood: true, coldChainRequired: true, perishable: true },
  },
  "fertilizer-agri-input": {
    id: "fertilizer-agri-input",
    titleFa: "کود و نهاده کشاورزی",
    titleEn: "Fertilizer & agri-inputs",
    descriptionFa: "کود، سموم و نهاده‌هایی که ممکن است محدودیت شیمیایی داشته باشند.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "certifications",
      "laboratory-testing",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: { isAgriInput: true, labSuggested: true, chemicalReview: true },
  },
  "chemical-dangerous-goods": {
    id: "chemical-dangerous-goods",
    titleFa: "مواد شیمیایی و کالای خطرناک",
    titleEn: "Chemicals & dangerous goods",
    descriptionFa: "شیمیایی، گوگرد و کالاهایی با الزام DG/MSDS.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "dangerous-goods",
      "certifications",
      "laboratory-testing",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: { dangerousGoods: true, labSuggested: true },
  },
  minerals: {
    id: "minerals",
    titleFa: "مواد معدنی",
    titleEn: "Minerals",
    descriptionFa: "مواد معدنی و فلزی با تمرکز بر آنالیز و اسناد تجاری.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "certifications",
      "laboratory-testing",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: { isMineral: true, labSuggested: true },
  },
  "industrial-parts": {
    id: "industrial-parts",
    titleFa: "قطعات صنعتی",
    titleEn: "Industrial parts",
    descriptionFa: "قطعات و اجزای صنعتی عمومی.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "certifications",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: {},
  },
  machinery: {
    id: "machinery",
    titleFa: "ماشین‌آلات",
    titleEn: "Machinery",
    descriptionFa: "ماشین‌آلات و تجهیزات صنعتی.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "certifications",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: { isMachinery: true },
  },
  "construction-materials": {
    id: "construction-materials",
    titleFa: "مصالح ساختمانی",
    titleEn: "Construction materials",
    descriptionFa: "مصالح و محصولات ساختمانی.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "certifications",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: {},
  },
  "textile-consumer-goods": {
    id: "textile-consumer-goods",
    titleFa: "نساجی و کالای مصرفی",
    titleEn: "Textile & consumer goods",
    descriptionFa: "پوشاک، نساجی و کالاهای مصرفی.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "certifications",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "destination-labeling",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: { labelingRequired: true },
  },
  general: {
    id: "general",
    titleFa: "مسیر عمومی صادرات",
    titleEn: "General export pathway",
    descriptionFa: "قالب پایه وقتی خانواده کالا مشخص نیست.",
    stepCodes: [
      "product-readiness",
      "market-selection",
      "hs-code",
      "export-restrictions",
      "certifications",
      "pricing",
      "buyer-verification",
      "contract",
      "payment-method",
      "incoterms",
      "export-packaging",
      "customs-documents",
      "customs-declaration",
      "freight-selection",
      "cargo-insurance",
      "shipment",
      "delivery",
      "post-shipment",
    ],
    defaultFlags: {},
  },
};

/** Map 6 practical starter packs requested in product brief → family ids */
const STARTER_PACKS = [
  { id: "agro-raw", familyId: "agro-raw" },
  { id: "food-processed", familyId: "food-processed" },
  { id: "perishable-cold-chain", familyId: "perishable-cold-chain" },
  { id: "fertilizer-chemical-dg", familyId: "chemical-dangerous-goods", also: ["fertilizer-agri-input"] },
  { id: "minerals", familyId: "minerals" },
  { id: "industrial-general", familyId: "industrial-parts", also: ["machinery", "general"] },
];

function getFamilyTemplate(familyId) {
  return FAMILY_TEMPLATES[familyId] || FAMILY_TEMPLATES.general;
}

module.exports = { FAMILY_TEMPLATES, STARTER_PACKS, getFamilyTemplate };
